### ISSUE TITLE
Make durationMS less redundant (currently have to change it 2x in scene + 1x in render panel)

### ISSUE THREAD

**Issue by RaymondDashWu** [CodeLabs-Hubble-gl/hubble.gl#44]

**Comment by chrisgervang** [comment]
This topic is only partially closed. The user still cannot edit the timing
in UI. Is there another task for that?

**Comment by RaymondDashWu** [comment]
Ah you're right. I'll rename this one to match what you did and repurpose another card that we have "Agree on how the duration should be implemented"
